# JobSpy LLM Letters Configuration - FIXED VERSION
# Configuration for automated job search and cover letter generation

search:
  # Basic search parameters
  query: "Werkstudent Informatik"
  location: "55286 Sulzheim, Deutschland"  # More specific location with postal code
  
  # Google-specific search term (CRITICAL: Must be very specific)
  # Copy this EXACTLY from google.com/jobs after applying filters manually
  google_search_term: "jobs Mainz Werkstudent Informatik"
  
  # Job sources to scrape from
  sources: ["indeed", "linkedin", "google"]
  
  # Search parameters
  results_wanted: 30        # Reduced for LinkedIn to avoid rate limiting
  distance: 31              # 31 miles ≈ 50km (miles to km conversion)
  
  # Time filtering - COMMENTED OUT to avoid conflicts with LinkedIn
  # hours_old: 168          # Conflicts with LinkedIn
  
  # Job type filtering (use this OR hours_old, never both)
  job_type: null            # fulltime, parttime, internship, contract
  remote: null              # true/false/null for remote preference
  
  # Site-specific parameters
  country_indeed: "Germany"          # Required for Indeed/Glassdoor
  linkedin_fetch_description: false  # Keep false for speed
  
  # CRITICAL: Proxies for LinkedIn (without these, LinkedIn will fail)
  # Option 1: Free proxies (less reliable)
  yamlproxies:
    - "proxy-server.scraperapi.com:8001"
    - "rotating-residential.proxyrack.com:9000"
  
  # Option 2: Comment out proxies to test without LinkedIn first
  # If LinkedIn fails, uncomment and add real proxy servers
  # proxies: []
  
  # Technical parameters
  verbose: 1                # 0=errors only, 1=errors+warnings, 2=all logs
  description_format: "markdown"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

scoring:
  # Keyword scoring weights
  keywords:
    # Core skills (high weight)
    Python: 4
    "Data Analytics": 3
    "Datenanalyse": 3
    Linux: 3
    "Werkstudent": 4        # Increased weight for this important term
    "duales Studium": 3
    "dual": 3
    
    # Important skills (medium weight)
    SQL: 2
    Docker: 2
    "Business Intelligence": 2
    "Power BI": 2
    Automatisierung: 2
    "IT-Infrastruktur": 2
    "Teilzeit": 3           # Important for your situation
    "20 Stunden": 3
    "Machine Learning": 2
    
    # Location preferences (bonus points)
    Mainz: 2
    Wiesbaden: 1
    Frankfurt: 1
    "Remote": 3
    "Homeoffice": 3
    
    # Nice to have (low weight)
    Git: 1
    Bash: 1
    AI: 1
    "Künstliche Intelligenz": 1
    Energiewende: 1
    Digitalisierung: 1
    JavaScript: 1
    React: 1
    
    # Negative keywords (penalties)
    "Vollzeit": -2          # Penalty for full-time only positions
    "40 Stunden": -2
    "Senior": -4            # Strong penalty for senior positions
    "Lead": -3
    "Leiter": -3
    "5+ Jahre": -3
    "mehrjährig": -2
    "abgeschlossen": -2     # Penalty for requiring completed degree
    
  # Bonus/malus scoring
  bonus_remote: 3           # Extra points for remote jobs
  malus_senior: 4           # Penalty for senior positions
  
  # Filtering
  min_score: -1             # Slightly higher minimum score
  top_k: 25                 # Maximum number of jobs to process

llm:
  # Model configuration
  model: "gpt-4o-mini"      # Fast and cost-effective
  temperature: 0.7          # Good balance of creativity and consistency
  max_tokens: 1200          # Adequate for cover letters
  
  # Language and style
  language: "de"
  target_length: 1800       # Target character count for cover letters
  tone: "professionell, präzise, selbstbewusst aber respektvoll"
  
  # Personal context (customize this!)
  dual_study_context: |
    Ich befinde mich im 5. Semester eines dualen Informatikstudiums an der IU Internationale Hochschule 
    (Abschluss voraussichtlich März 2027) und suche einen neuen Praxispartner ab Oktober 2025. 
    Idealerweise eine werkstudentenähnliche Anstellung mit 20 Std/Woche während der Vorlesungszeit 
    und Vollzeit in den Semesterferien, bei der Studiengebühren übernommen werden. 
    Mein Fokus liegt auf datengetriebenen Lösungen, Automatisierung und IT-Infrastruktur.
    Ich wohne in 55286 Sulzheim (bei Mainz) und bin bereit für Hybridarbeit oder Remote-Arbeit.

files:
  # Template file paths (relative to script directory)
  resume_path: "data/resume.md"
  template_letter_path: "data/template_letter.md"
  example_letter_path: "data/example_letter.md"

output:
  # Output configuration
  out_dir: "out"
  save_jobs_csv: true       # Save all jobs to CSV
  save_raw_data: true       # Save raw scraping results for debugging

# Advanced settings
advanced:
  max_retries: 3            # Retry failed requests
  request_delay: 2.0        # Increased delay between requests (helps with rate limiting)
  enable_caching: false     # Cache results (experimental)

# TROUBLESHOOTING GUIDE:
# 
# 1. LinkedIn Issues:
#    - LinkedIn REQUIRES proxies for consistent results
#    - Reduce results_wanted to 10-20 for LinkedIn
#    - Use different proxy servers
#    - Try running without LinkedIn first, then add it back
#
# 2. Google Jobs Issues:
#    - Go to google.com/jobs manually
#    - Enter your search terms and apply filters
#    - Copy the EXACT search string that appears
#    - Paste it as google_search_term above
#
# 3. No Results:
#    - Try broader search terms first
#    - Test with just Indeed initially
#    - Check if location format is correct
#    - Increase distance if needed
#
# 4. Rate Limiting (429 errors):
#    - Increase request_delay to 3-5 seconds
#    - Reduce results_wanted
#    - Add working proxy servers
#    - Wait between scraping sessions